/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Image;
import java.util.Arrays;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Chimchanoudom
 */
public class KlaKlouk extends javax.swing.JFrame {

    /**
     * Creates new form KlaKlouk
     */
    public KlaKlouk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtKlouk = new javax.swing.JTextField();
        btnKlouk = new javax.swing.JButton();
        btnHen = new javax.swing.JButton();
        txthen = new javax.swing.JTextField();
        txtbkk = new javax.swing.JTextField();
        btnbkk = new javax.swing.JButton();
        txtKdam = new javax.swing.JTextField();
        btnkdam = new javax.swing.JButton();
        txtfish = new javax.swing.JTextField();
        lblKla = new javax.swing.JLabel();
        lblbkk = new javax.swing.JLabel();
        lblKlouk = new javax.swing.JLabel();
        lblKdam = new javax.swing.JLabel();
        lblHen = new javax.swing.JLabel();
        lblFish = new javax.swing.JLabel();
        txtKla = new javax.swing.JTextField();
        btnfish = new javax.swing.JButton();
        btnKla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt100 = new javax.swing.JTextField();
        btn100Plus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn100Minus = new javax.swing.JButton();
        btn500Minus = new javax.swing.JButton();
        txt500 = new javax.swing.JTextField();
        btn500Plus = new javax.swing.JButton();
        btn1000Plus = new javax.swing.JButton();
        txt1000 = new javax.swing.JTextField();
        btn1000Minus = new javax.swing.JButton();
        btn2000Plus = new javax.swing.JButton();
        txt2000 = new javax.swing.JTextField();
        btn2000Minus = new javax.swing.JButton();
        btn5000Plus = new javax.swing.JButton();
        txt5000 = new javax.swing.JTextField();
        btn5000Minus = new javax.swing.JButton();
        btn10000Plus = new javax.swing.JButton();
        txt10000 = new javax.swing.JTextField();
        btn10000Minus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFMoney = new javax.swing.JFormattedTextField();
        txtFWin = new javax.swing.JFormattedTextField();
        txtFLost = new javax.swing.JFormattedTextField();
        txtFAmount = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtKlouk.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        txtKlouk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKlouk.setText("0");
        txtKlouk.setFocusable(false);

        btnKlouk.setBackground(new java.awt.Color(255, 51, 51));
        btnKlouk.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnKlouk.setText("-");

        btnHen.setBackground(new java.awt.Color(255, 51, 51));
        btnHen.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnHen.setText("-");

        txthen.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        txthen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthen.setText("0");
        txthen.setFocusable(false);

        txtbkk.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        txtbkk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbkk.setText("0");
        txtbkk.setFocusable(false);

        btnbkk.setBackground(new java.awt.Color(255, 51, 51));
        btnbkk.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnbkk.setText("-");

        txtKdam.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        txtKdam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKdam.setText("0");
        txtKdam.setFocusable(false);

        btnkdam.setBackground(new java.awt.Color(255, 51, 51));
        btnkdam.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnkdam.setText("-");

        txtfish.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        txtfish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfish.setText("0");
        txtfish.setFocusable(false);

        lblKla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-1.jpg"))); // NOI18N
        lblKla.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153))));
        lblKla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKlaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblKlaMousePressed(evt);
            }
        });

        lblbkk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-4.jpg"))); // NOI18N
        lblbkk.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153))));

        lblKlouk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-2.jpg"))); // NOI18N
        lblKlouk.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153))));

        lblKdam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-5.jpg"))); // NOI18N
        lblKdam.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153))));

        lblHen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-3.jpg"))); // NOI18N
        lblHen.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153))));

        lblFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Untitled-6.jpg"))); // NOI18N
        lblFish.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153))));

        txtKla.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        txtKla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKla.setText("0");
        txtKla.setFocusable(false);

        btnfish.setBackground(new java.awt.Color(255, 51, 51));
        btnfish.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnfish.setText("-");

        btnKla.setBackground(new java.awt.Color(255, 51, 51));
        btnKla.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnKla.setText("-");

        jLabel1.setFont(new java.awt.Font("Khmer Rotanak Angkor", 0, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ល្បែងខ្លាឃ្លោក");

        jPanel1.setBackground(new java.awt.Color(49, 77, 155));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/100(2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        txt100.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt100.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt100.setText("0");
        txt100.setFocusable(false);
        txt100.setName("100"); // NOI18N

        btn100Plus.setBackground(new java.awt.Color(0, 153, 0));
        btn100Plus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn100Plus.setForeground(new java.awt.Color(255, 255, 255));
        btn100Plus.setText("+");
        btn100Plus.setEnabled(false);
        btn100Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100PlusActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/500(3).jpg"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1000(4).jpg"))); // NOI18N
        jLabel5.setText("jLabel3");
        jLabel5.setName("1000"); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2000(5).jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        jLabel6.setName("2000"); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5000(6).jpg"))); // NOI18N
        jLabel7.setText("jLabel3");
        jLabel7.setName("5000"); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/10000(1).jpg"))); // NOI18N
        jLabel8.setText("jLabel3");

        btn100Minus.setBackground(new java.awt.Color(255, 0, 0));
        btn100Minus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn100Minus.setForeground(new java.awt.Color(255, 255, 255));
        btn100Minus.setText("-");
        btn100Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100MinusActionPerformed(evt);
            }
        });

        btn500Minus.setBackground(new java.awt.Color(255, 0, 0));
        btn500Minus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn500Minus.setForeground(new java.awt.Color(255, 255, 255));
        btn500Minus.setText("-");
        btn500Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500MinusActionPerformed(evt);
            }
        });

        txt500.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt500.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt500.setText("0");
        txt500.setFocusable(false);
        txt500.setName("500"); // NOI18N

        btn500Plus.setBackground(new java.awt.Color(0, 153, 0));
        btn500Plus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn500Plus.setForeground(new java.awt.Color(255, 255, 255));
        btn500Plus.setText("+");
        btn500Plus.setEnabled(false);
        btn500Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500PlusActionPerformed(evt);
            }
        });

        btn1000Plus.setBackground(new java.awt.Color(0, 153, 0));
        btn1000Plus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn1000Plus.setForeground(new java.awt.Color(255, 255, 255));
        btn1000Plus.setText("+");
        btn1000Plus.setEnabled(false);
        btn1000Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000PlusActionPerformed(evt);
            }
        });

        txt1000.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt1000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1000.setText("0");
        txt1000.setFocusable(false);
        txt1000.setName("1000"); // NOI18N

        btn1000Minus.setBackground(new java.awt.Color(255, 0, 0));
        btn1000Minus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn1000Minus.setForeground(new java.awt.Color(255, 255, 255));
        btn1000Minus.setText("-");
        btn1000Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000MinusActionPerformed(evt);
            }
        });

        btn2000Plus.setBackground(new java.awt.Color(0, 153, 0));
        btn2000Plus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn2000Plus.setForeground(new java.awt.Color(255, 255, 255));
        btn2000Plus.setText("+");
        btn2000Plus.setEnabled(false);
        btn2000Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000PlusActionPerformed(evt);
            }
        });

        txt2000.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt2000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2000.setText("0");
        txt2000.setFocusable(false);
        txt2000.setName("2000"); // NOI18N

        btn2000Minus.setBackground(new java.awt.Color(255, 0, 0));
        btn2000Minus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn2000Minus.setForeground(new java.awt.Color(255, 255, 255));
        btn2000Minus.setText("-");
        btn2000Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000MinusActionPerformed(evt);
            }
        });

        btn5000Plus.setBackground(new java.awt.Color(0, 153, 0));
        btn5000Plus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn5000Plus.setForeground(new java.awt.Color(255, 255, 255));
        btn5000Plus.setText("+");
        btn5000Plus.setEnabled(false);
        btn5000Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000PlusActionPerformed(evt);
            }
        });

        txt5000.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt5000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5000.setText("0");
        txt5000.setFocusable(false);
        txt5000.setName("5000"); // NOI18N

        btn5000Minus.setBackground(new java.awt.Color(255, 0, 0));
        btn5000Minus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn5000Minus.setForeground(new java.awt.Color(255, 255, 255));
        btn5000Minus.setText("-");
        btn5000Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000MinusActionPerformed(evt);
            }
        });

        btn10000Plus.setBackground(new java.awt.Color(0, 153, 0));
        btn10000Plus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn10000Plus.setForeground(new java.awt.Color(255, 255, 255));
        btn10000Plus.setText("+");
        btn10000Plus.setEnabled(false);
        btn10000Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000PlusActionPerformed(evt);
            }
        });

        txt10000.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt10000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10000.setText("0");
        txt10000.setFocusable(false);
        txt10000.setName("10000"); // NOI18N

        btn10000Minus.setBackground(new java.awt.Color(255, 0, 0));
        btn10000Minus.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn10000Minus.setForeground(new java.awt.Color(255, 255, 255));
        btn10000Minus.setText("-");
        btn10000Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000MinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn100Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn100Minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn2000Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt2000, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn2000Minus)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn500Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn500Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn1000Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt1000, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1000Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btn5000Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5000, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5000Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn10000Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt10000, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10000Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1000Minus)
                                .addComponent(btn1000Plus)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn100Plus)
                                .addComponent(btn100Minus))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn500Plus)
                            .addComponent(btn500Minus))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt10000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn10000Plus)
                        .addComponent(btn10000Minus)
                        .addComponent(btn5000Minus)
                        .addComponent(txt5000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn5000Plus))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt2000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2000Plus)
                        .addComponent(btn2000Minus)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(49, 77, 155));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        jLabel9.setFont(new java.awt.Font("AKbalthom Kbach", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("លុយដើម៖");

        jLabel10.setFont(new java.awt.Font("AKbalthom Kbach", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("លុយឈ្នះ៖");

        jLabel11.setFont(new java.awt.Font("AKbalthom Kbach", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("លុយចាញ់៖");

        jLabel12.setFont(new java.awt.Font("AKbalthom Kbach", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("លុយចាក់សរុប៖");

        txtFMoney.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFMoney.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFMoney.setText("0");
        txtFMoney.setFocusable(false);
        txtFMoney.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N

        txtFWin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFWin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFWin.setText("0");
        txtFWin.setFocusable(false);
        txtFWin.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N

        txtFLost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFLost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFLost.setText("0");
        txtFLost.setFocusable(false);
        txtFLost.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N

        txtFAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtFAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFAmount.setText("0");
        txtFAmount.setFocusable(false);
        txtFAmount.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFWin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFLost)))
                        .addGap(8, 8, 8))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFWin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFLost, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(txtFAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(49, 77, 155));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 4, true));

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 4, true));

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 4, true));

        btnStart.setBackground(new java.awt.Color(0, 204, 102));
        btnStart.setFont(new java.awt.Font("AKbalthom Freehand", 0, 18)); // NOI18N
        btnStart.setText("ក្រលុក");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtKla, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btnKla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtKlouk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKlouk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKlouk))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txthen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtbkk, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbkk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblbkk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtKdam, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnkdam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKdam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFish)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtfish, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnfish, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblKla)
                                    .addComponent(lblKlouk)))
                            .addComponent(lblHen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHen)
                            .addComponent(txtKlouk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKlouk)
                            .addComponent(txthen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKla)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbkk)
                            .addComponent(lblKdam)
                            .addComponent(lblFish))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtbkk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnbkk)
                                .addComponent(txtKdam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnkdam)
                                .addComponent(txtfish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnfish)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(txtKlouk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnKlouk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txthen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtbkk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnbkk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtKdam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnkdam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtfish, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblKla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblbkk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblKlouk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblKdam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblHen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblFish, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtKla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnfish, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnKla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    ArrayList<JTextField>Txt=new ArrayList<>();
    ArrayList  KLa=new ArrayList();
    ArrayList  Klouk=new ArrayList();
    ArrayList  Hen=new ArrayList();
    ArrayList  Lobster=new ArrayList();
    ArrayList  Kdam=new ArrayList();
    ArrayList  Fish=new ArrayList();

    
    @SuppressWarnings("empty-statement")
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      JButton[]  Plus={btn100Plus,btn500Plus,btn1000Plus,btn2000Plus,btn5000Plus,btn10000Plus};
      JButton[]  Minus={btn100Minus,btn500Minus,btn1000Minus,btn2000Minus,btn5000Minus,btn10000Minus};
        JTextField[]Ftxt={txt100,txt500,txt1000,txt2000,txt5000,txt10000};
        Txt.addAll(Arrays.asList(Ftxt));
    this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    this.setResizable(false);
    KKClass.setFtxt(Txt);
   KKClass.getBtnPlus(Plus);
   KKClass.getBtnMinus(Minus);
    txtFMoney.setText("20000");
    txtFMoney.setFocusable(false);
    KKClass.EnableBtnPlus(txtFMoney,"-");
    
    //pov
    KKClass.txtUser=new JTextField[]{txtKla,txtKlouk,txthen,txtbkk,txtKdam,txtfish};
    
    KKClass.lbResult=new JLabel[]{lbl1,lbl2,lbl3};
    
    for(int i=1;i<=6;i++){
        String filePath="resources/Untitled-"+i+".jpg";
        KKClass.img.add(new ImageIcon(getClass().getClassLoader().getResource(filePath)));
    }
   
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btn100PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100PlusActionPerformed
        //JOptionPane.showMessageDialog(this, KKClass.Check(txtFMoney));
        if(KKClass.Check(txtFMoney.getText())==true){
          //  KKClass.PlusorMinus(txt100,txtFMoney,"+");
              KKClass.PlusAmount(txtFAmount,"+", txt100 ,txtFMoney);
        KKClass.EnableBtnPlus(txtFMoney,"+");
      
        }
         else
            JOptionPane.showMessageDialog(btn100Plus, "NO Money!");

    // TODO add your handling code here:
    }//GEN-LAST:event_btn100PlusActionPerformed

    private void btn100MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100MinusActionPerformed
        // TODO add your handling code here:
        if(KKClass.Check(txt100.getText())==true){
            KKClass.MinusAmount(txtFAmount, txt100, txtFMoney);
            KKClass.EnableBtnPlus(txtFMoney,"-");
        
        }
         else
            JOptionPane.showMessageDialog(btn100Plus, "No Money!");
    }//GEN-LAST:event_btn100MinusActionPerformed

    private void btn500PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500PlusActionPerformed
        // TODO add your handling code here:
        if(KKClass.Check(txtFMoney.getText())==true){
           // txtFAmount.setText(KKClass.PlusAmount(txtFAmount,"+", txt500.getName()));
            //KKClass.PlusorMinus(txt500,txtFMoney,"+");
                  KKClass.PlusAmount(txtFAmount,"+", txt500 ,txtFMoney);
            KKClass.EnableBtnPlus(txtFMoney,"+");
        }
         else
            JOptionPane.showMessageDialog(btn500Plus, "No Money!");
    }//GEN-LAST:event_btn500PlusActionPerformed

    private void btn500MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500MinusActionPerformed
        // TODO add your handling code here:
        if(KKClass.Check(txt500.getText())==true){
  KKClass.MinusAmount(txtFAmount, txt500, txtFMoney);
           // KKClass.PlusorMinus(txt500,txtFMoney,"-");
            KKClass.EnableBtnPlus(txtFMoney,"-");
        }
         else
            JOptionPane.showMessageDialog(btn500Minus, "No Money!");
    }//GEN-LAST:event_btn500MinusActionPerformed

    private void btn1000PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000PlusActionPerformed
        // TODO add your handling code here:
         if(KKClass.Check(txtFMoney.getText())==true){
           // KKClass.PlusorMinus(txt1000,txtFMoney,"+");
                   KKClass.PlusAmount(txtFAmount,"+", txt1000 ,txtFMoney);
            KKClass.EnableBtnPlus(txtFMoney,"+");
         }
         else
            JOptionPane.showMessageDialog(btn1000Plus, "No Money!");
    }//GEN-LAST:event_btn1000PlusActionPerformed

    private void btn1000MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000MinusActionPerformed
        // TODO add your handling code here:
        if(KKClass.Check(txt1000.getText())==true){
              KKClass.MinusAmount(txtFAmount, txt1000, txtFMoney);
          //  KKClass.PlusorMinus(txt1000,txtFMoney,"-");
            KKClass.EnableBtnPlus(txtFMoney,"-");
        }
         else
            JOptionPane.showMessageDialog(btn1000Minus, "No Money!");
    }//GEN-LAST:event_btn1000MinusActionPerformed

    private void btn2000PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000PlusActionPerformed
        // TODO add your handling code here:
        if(KKClass.Check(txtFMoney.getText())==true){
            //KKClass.PlusorMinus(txt2000,txtFMoney,"+");
                  KKClass.PlusAmount(txtFAmount,"+", txt2000 ,txtFMoney);
            KKClass.EnableBtnPlus(txtFMoney,"+");
        }
         else
            JOptionPane.showMessageDialog(btn2000Plus, "No Money!");
    }//GEN-LAST:event_btn2000PlusActionPerformed

    private void btn2000MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000MinusActionPerformed
        // TODO add your handling code here:
        if(KKClass.Check(txt2000.getText())==true){
              KKClass.MinusAmount(txtFAmount, txt2000, txtFMoney);
            //KKClass.PlusorMinus(txt2000,txtFMoney,"-");
            KKClass.EnableBtnPlus(txtFMoney,"-");
        }
         else
            JOptionPane.showMessageDialog(btn2000Minus, "No Money!");
    }//GEN-LAST:event_btn2000MinusActionPerformed

    private void btn5000PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000PlusActionPerformed
        // TODO add your handling code here:
         if(KKClass.Check(txtFMoney.getText())==true){
            //KKClass.PlusorMinus(txt5000,txtFMoney,"+");
                  KKClass.PlusAmount(txtFAmount,"+", txt5000 ,txtFMoney);
            KKClass.EnableBtnPlus(txtFMoney,"+");
         }
         else
            JOptionPane.showMessageDialog(btn5000Plus, "No Money!");
    }//GEN-LAST:event_btn5000PlusActionPerformed

    private void btn5000MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000MinusActionPerformed
        // TODO add your handling code here:
         if(KKClass.Check(txt5000.getText())==true){
               KKClass.MinusAmount(txtFAmount, txt5000, txtFMoney);
          //  KKClass.PlusorMinus(txt5000,txtFMoney,"-");
            KKClass.EnableBtnPlus(txtFMoney,"-");
         }
         else
            JOptionPane.showMessageDialog(btn5000Minus, "No Money!");
    }//GEN-LAST:event_btn5000MinusActionPerformed

    private void btn10000PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000PlusActionPerformed
        // TODO add your handling code here:
         if(KKClass.Check(txtFMoney.getText())==true){
           // KKClass.PlusorMinus(txt10000,txtFMoney,"+");
                   KKClass.PlusAmount(txtFAmount,"+", txt10000 ,txtFMoney);
            KKClass.EnableBtnPlus(txtFMoney,"+");
         }
         else
            JOptionPane.showMessageDialog(btn10000Plus, "No Money!");
    }//GEN-LAST:event_btn10000PlusActionPerformed

    private void btn10000MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000MinusActionPerformed
        // TODO add your handling code here:
         if(KKClass.Check(txt10000.getText())==true){
               KKClass.MinusAmount(txtFAmount, txt10000, txtFMoney);
            //KKClass.PlusorMinus(txt10000,txtFMoney,"-");
            KKClass.EnableBtnPlus(txtFMoney,"-");
         }
         else
            JOptionPane.showMessageDialog(btn10000Minus, "No Money!");
    }//GEN-LAST:event_btn10000MinusActionPerformed

    private void lblKlaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKlaMousePressed
       
    }//GEN-LAST:event_lblKlaMousePressed

    private void lblKlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKlaMouseClicked
        // TODO add your handling code here:
        KKClass.PutMoney(txtFAmount, txtKla);
    }//GEN-LAST:event_lblKlaMouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        if(btnStart.getText().equals("ក្រលុក")){
            if(!KKClass.ClickStart()){
                JOptionPane.showMessageDialog(null, "Please Input Money");
                return;
            }
                
            btnStart.setText("ឈប់");
            btnStart.setBackground(java.awt.Color.RED);
        }
        else{
            KKClass.ClickStop();
            btnStart.setText("ក្រលុក");
            btnStart.setBackground(java.awt.Color.GREEN);
            
            
        }
            
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlaKlouk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10000Minus;
    private javax.swing.JButton btn10000Plus;
    private javax.swing.JButton btn1000Minus;
    private javax.swing.JButton btn1000Plus;
    private javax.swing.JButton btn100Minus;
    private javax.swing.JButton btn100Plus;
    private javax.swing.JButton btn2000Minus;
    private javax.swing.JButton btn2000Plus;
    private javax.swing.JButton btn5000Minus;
    private javax.swing.JButton btn5000Plus;
    private javax.swing.JButton btn500Minus;
    private javax.swing.JButton btn500Plus;
    private javax.swing.JButton btnHen;
    private javax.swing.JButton btnKla;
    private javax.swing.JButton btnKlouk;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnbkk;
    private javax.swing.JButton btnfish;
    private javax.swing.JButton btnkdam;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblFish;
    private javax.swing.JLabel lblHen;
    private javax.swing.JLabel lblKdam;
    private javax.swing.JLabel lblKla;
    private javax.swing.JLabel lblKlouk;
    private javax.swing.JLabel lblbkk;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt1000;
    private javax.swing.JTextField txt10000;
    private javax.swing.JTextField txt2000;
    private javax.swing.JTextField txt500;
    private javax.swing.JTextField txt5000;
    private javax.swing.JFormattedTextField txtFAmount;
    private javax.swing.JFormattedTextField txtFLost;
    private javax.swing.JFormattedTextField txtFMoney;
    private javax.swing.JFormattedTextField txtFWin;
    private javax.swing.JTextField txtKdam;
    private javax.swing.JTextField txtKla;
    private javax.swing.JTextField txtKlouk;
    private javax.swing.JTextField txtbkk;
    private javax.swing.JTextField txtfish;
    private javax.swing.JTextField txthen;
    // End of variables declaration//GEN-END:variables
}
